steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/webjet-forecasting:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/webjet-forecasting:latest'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/webjet-forecasting:$COMMIT_SHA'

  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/webjet-forecasting:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'webjet-forecasting'
      - '--image=gcr.io/$PROJECT_ID/webjet-forecasting:$COMMIT_SHA'
      - '--region=australia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--max-instances=10'
      - '--port=8080'

images:
  - 'gcr.io/$PROJECT_ID/webjet-forecasting:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/webjet-forecasting:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  
timeout: 1200s